services:
  server:
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - HOSTING_PATH
    volumes:
      - ./server/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./server/conf/leprechaun.conf:/etc/nginx/conf.d/leprechaun.conf
      - ./server/conf/leprechaun.dev.conf:/etc/nginx/conf.d/leprechaun.dev.conf

  db:
    restart: unless-stopped
    volumes:
      - ./db/postgresql.conf:/app/postgresql.conf
      - ./db/pg_hba.conf:/app/pg_hba.conf

  cache:
    restart: unless-stopped
    volumes:
      - ./cache/redis.conf:/app/redis.conf

  api_gateway_private:
    restart: unless-stopped
    extends:
      file: docker-compose.shared.yaml
      service: node
    command: npm run dev:private
    volumes:
      - ./api/gateways:/app
      - /app/apps/public # exclude
      - /app/apps/ws # exclude
    environment:
      - IS_DEV=true
      - MAIL_SMPT_PORT_DEV

  api_gateway_public:
    restart: unless-stopped
    extends:
      file: docker-compose.shared.yaml
      service: node
    command: npm run dev:public
    volumes:
      - ./api/gateways:/app
      - /app/apps/private # exclude
      - /app/apps/ws # exclude
    environment:
      - IS_DEV=true
      - MAIL_SMPT_PORT_DEV

  api_gateway_ws:
    restart: unless-stopped
    extends:
      file: docker-compose.shared.yaml
      service: node
    command: npm run dev:ws
    volumes:
      - ./api/gateways:/app
      - /app/apps/private # exclude
      - /app/apps/public # exclude
    environment:
      - IS_DEV=true

  client_private:
    restart: unless-stopped
    container_name: leprechaun_client_private
    build:
      context: ./clients/private
      dockerfile: Dockerfile
    volumes:
      # - client_private_trans_hosting:/app/public/locales:rw
      # - ./translations/dist/client_private:/app/public/locales
      - ./clients/private:/app
    environment:
      - LANGS
      - VITE_APP_NAME=${APP_NAME}
      - DOMAIN_PUBLIC
      - VITE_DOMAIN_API=${DOMAIN_API}
      - VITE_DOMAIN_MEDIA=${DOMAIN_MEDIA}
    networks:
      - client
    depends_on:
      - api_gateway_private

  client_public:
    restart: unless-stopped
    extends:
      file: docker-compose.shared.yaml
      service: node
    working_dir: /app
    command: yarn dev
    volumes:
      # - client_public_trans_hosting:/app/src/public/locales:rw
      # - ./translations/dist/client_public:/app/src/public/locales
      - ./clients/public:/app
    environment:
      - IS_DEV=true
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  translations:
    restart: unless-stopped
    container_name: leprechaun_translations
    extends:
      file: docker-compose.shared.yaml
      service: node
    command: yarn dev
    volumes:
      - ./translations:/app
      # - client_public_trans_hosting:/app/dist/client_public:rw
      # - client_private_trans_hosting:/app/dist/client_private:rw
    environment:
      - LANGS

  mailcatcher:
    container_name: leprechaun_mailcatcher
    image: dockage/mailcatcher:0.9.0
    ports:
      - 1080:1080
    depends_on:
      - api_gateway_ws
      - api_gateway_public
      - api_gateway_private

# volumes:
#   client_public_trans_hosting:
#     driver: local
#   client_private_trans_hosting:
#     driver: local
