version: "3.8"

services:
  server:
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - HOSTING_PATH
    volumes:
      - ./server/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./server/conf/leprechaun.conf:/etc/nginx/conf.d/leprechaun.conf
      - ./server/conf/leprechaun.dev.conf:/etc/nginx/conf.d/leprechaun.dev.conf
    depends_on:
      - client_admin
      - client_user

  db:
    restart: unless-stopped
    volumes:
      - ./db/postgresql.conf:/app/postgresql.conf

  session:
    restart: unless-stopped
    volumes:
      - ./session/redis.conf:/app/redis.conf

  cache:
    restart: unless-stopped
    volumes:
      - ./cache/redis.conf:/app/redis.conf

  api:
    restart: unless-stopped
    image: node:16.17-alpine
    working_dir: /app
    command: yarn dev
    volumes:
      - ./api:/app
    environment:
      - IS_DEV=true

  manticore:
    restart: unless-stopped
    ports:
      - ${MANTICORE_PORT}:${MANTICORE_PORT}

  client_user:
    restart: unless-stopped
    image: node:16.17-alpine
    working_dir: /app
    command: npm run serve:docker
    volumes:
      - ./clients/user:/app
    environment:
      - IS_DEV=true

  client_admin:
    container_name: leprechaun_client_admin
    restart: unless-stopped
    image: node:16.17-alpine
    working_dir: /app
    volumes:
      - ./clients/admin:/app
    command: npm run serve:docker
    environment:
      - LANGS
      - APP_NAME
      - DOMAIN
      - DOMAIN_API
      - DOMAIN_MEDIA
    depends_on:
      - api
