services:
  server:
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - HOSTING_PATH
    volumes:
      - ./server/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./server/conf/leprechaun.conf:/etc/nginx/conf.d/leprechaun.conf
      - ./server/conf/leprechaun.dev.conf:/etc/nginx/conf.d/leprechaun.dev.conf

  db:
    restart: unless-stopped
    volumes:
      - ./db/postgresql.conf:/app/postgresql.conf
      - ./db/pg_hba.conf:/app/pg_hba.conf

  cache:
    restart: unless-stopped
    volumes:
      - ./cache/redis.conf:/app/redis.conf

  api:
    extends:
      file: docker-compose.shared.yaml
      service: node
    restart: unless-stopped
    command: yarn dev
    volumes:
      - ./api:/app
    environment:
      - IS_DEV=true

  # client_user:
  #   extends:
  #     file: docker-compose.shared.yaml
  #     service: node
  #   restart: unless-stopped
  #   volumes:
  #     # - ./clients/user:/app
  #     - ./clients/user_v2:/app
  #   environment:
  #     - IS_DEV=true

  client_admin:
    container_name: leprechaun_client_admin
    restart: unless-stopped
    build:
      context: ./clients/admin_v2
      dockerfile: Dockerfile
    # extends:
    #   file: docker-compose.shared.yaml
    #   service: node
    volumes:
      - ./clients/admin_v2:/app
    environment:
      - LANGS
      - VITE_APP_NAME=${APP_NAME}
      - DOMAIN
      - VITE_DOMAIN_API=${DOMAIN_API}
      - DOMAIN_MEDIA
    ports:
      - "5173:80"
    networks:
      - client
    depends_on:
      - server
