version: '3.8'

services:
  postgres:
    restart: unless-stopped
    volumes:
      - ./postgres/postgresql.conf:/app/postgresql.conf

  # redis:
  #   restart: unless-stopped

  # client:
  #   restart: unless-stopped

  server:
    restart: unless-stopped
    build: ./server
    volumes:
      - ./server:/app
    environment:
      - IS_DEV=true

  nginx:
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/leprechaun.conf:/etc/nginx/conf.d/leprechaun.conf

  # adm:
  #   restart: unless-stopped
