version: '3.8'

services:
  postgres:
    restart: on-failure:5

  redis:
    restart: on-failure:5

  server:
    restart: on-failure:5
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    environment:
      - IS_DEV=false
      - DEV_MAIL_RECIEVER

  manticore:
    restart: on-failure:5

  client:
    restart: on-failure:5
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    environment:
      - IS_DEV=false

  nginx:
    restart: on-failure:5
    build:
      dockerfile: Dockerfile.prod
    ports:
      - 84:80

  admin:
    restart: on-failure:5
    build:
      context: ./admin
      dockerfile: Dockerfile.prod
