services:

  ### INFRA

  server:
    container_name: leprechaun-infra-server
    networks:
      server_infra:
        aliases:
          - api.leprechaun.loc
          - leprechaun.loc
    ports:
      - ${WEB_SERVER_PORT}:80
    volumes:
      - ./infra/server/.http_auth:/etc/nginx/.http_auth
    depends_on:
      - app_api
      - app_client

  events:
    container_name: leprechaun-infra-events
    image: rabbitmq:4-management-alpine
    ports:
      - ${EVENTS_PORT_EXPOSE}:${EVENTS_PORT}
    networks:
      - api_domain

#   s3:
#     image: minio/minio
#     container_name: leprechaun-s3
#     networks:
#       - api
#     environment:
#       - MINIO_ROOT_USER=${S3_USER}
#       - MINIO_ROOT_PASSWORD=${S3_PASSWORD}
#     volumes:
#       - ./s3/data:/data
#       - ./s3/entrypoint.sh:/docker-entrypoint-init.d/entrypoint.sh
#     entrypoint: /docker-entrypoint-init.d/entrypoint.sh ${S3_USER} ${S3_PASSWORD} ${S3_PORT} ${S3_PORT_UI}

#   db_main:
#     container_name: leprechaun_db_main
#     networks:
#       - api
#       - db
#     build:
#       context: ./db/main
#       dockerfile: Dockerfile
#     ports:
#       - ${DB_PORT_EXPOSE}:${DB_PORT}
#     environment:
#       - POSTGRES_PASSWORD=${DB_PASSWORD}
#       - POSTGRES_USER=${DB_USER}
#       - POSTGRES_DATABASE=${DB_DATABASE}

#   db_cache:
#     container_name: leprechaun_db_cache
#     networks:
#       - api
#     build:
#       context: ./db/cache
#       dockerfile: Dockerfile
#       args:
#         - REDIS_PASSWORD=${CACHE_PASSWORD}
#     environment:
#       - REDIS_PASSWORD=${CACHE_PASSWORD}
#     ports:
#       - ${CACHE_PORT_EXPOSE}:${CACHE_PORT}

  ### APSS

  #   api_gateway_ws:
#     container_name: leprechaun_api_gateway_ws
#     networks:
#       - api
#     environment:
#       - SESSION_COOKIE_SECRET
#       - SOCKET_HOST
#       - SOCKET_PORT
#       - SOCKET_USER
#       - SOCKET_PASSWORD
#       - SOCKET_DB_NUMBER
#       - DOMAIN_PUBLIC
#       - DOMAIN_PRIVATE
#       - BROKER_NET_HOST
#       - BROKER_NET_PORT
#     depends_on:
#       - db_cache

  app_api:
    container_name: leprechaun-app-api
    networks:
      - server_infra
      - api_domain
    environment:
      - APP_NAME
      - HOST_NAME
      - LANGS
      - DOMAIN_PUBLIC
      - DOMAIN_PRIVATE
      - JWT_ACCESS_TOKEN_KEY
      - JWT_ACCESS_TOKEN_TTL
      - AUTH_SERVICE_CLIENT_HOST
      - AUTH_SERVICE_CLIENT_PORT
      - USER_SERVICE_CLIENT_HOST
      - USER_SERVICE_CLIENT_PORT
      - PROPGROUP_SERVICE_CLIENT_HOST
      - PROPGROUP_SERVICE_CLIENT_PORT
      - CATEGORY_SERVICE_CLIENT_HOST
      - CATEGORY_SERVICE_CLIENT_PORT
      - PRODUCT_SERVICE_CLIENT_HOST
      - PRODUCT_SERVICE_CLIENT_PORT
      - WISHLIST_SERVICE_CLIENT_HOST
      - WISHLIST_SERVICE_CLIENT_PORT
      - HISTORY_SERVICE_CLIENT_HOST
      - HISTORY_SERVICE_CLIENT_PORT
      - SUBSCRIPTION_SERVICE_CLIENT_HOST
      - SUBSCRIPTION_SERVICE_CLIENT_PORT
    depends_on:
      - events
      - service_auth_client
      - service_propgroup_client
      - service_user_client
      - service_trans_client
      - service_category_client
      - service_product_client
      - service_wishlist_client
      - service_history_client
      - service_subscription_client

  app_client:
    container_name: leprechaun-app-client
    networks:
      - server_infra
    environment:
      - APP_NAME
      - LANGS
      - NEXT_PUBLIC_LANGS=${LANGS}
      - DOMAIN_PUBLIC
      - DOMAIN_API
      - NEXT_PUBLIC_DOMAIN_API=${DOMAIN_API}
      - CURRENCY_SYMBOL
    depends_on:
      - app_api

  ### SERVICES

  service_auth_client:
    container_name: leprechaun-service-auth-client
    environment:
      - AUTH_SERVICE_CLIENT_PORT
      - USER_SERVICE_CLIENT_HOST
      - USER_SERVICE_CLIENT_PORT
      - JWT_ACCESS_TOKEN_KEY
      - JWT_ACCESS_TOKEN_TTL
      - JWT_REFRESH_TOKEN_KEY
      - JWT_REFRESH_TOKEN_TTL
    networks:
      - api_domain
      - auth_service

  service_user_client:
    container_name: leprechaun-service-user-client
    environment:
      - USER_SERVICE_CLIENT_PORT
      - POSTGRES_USER=${USER_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${USER_SERVICE_DB_PASSWORD}
      - POSTGRES_HOST=${USER_SERVICE_DB_HOST}
      - POSTGRES_PORT=${USER_SERVICE_DB_PORT}
      - POSTGRES_DATABASE=${USER_SERVICE_DB_DATABASE}
    networks:
      - api_domain
      - user_service
    depends_on:
      - service_user_db

  service_user_db:
    container_name: leprechaun-service-user-db
    build:
      context: ./services/user/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=${USER_SERVICE_DB_PASSWORD}
      - POSTGRES_USER=${USER_SERVICE_DB_USER}
      - POSTGRES_DATABASE=${USER_SERVICE_DB_DATABASE}
    ports:
      - ${USER_SERVICE_DB_PORT_EXPOSE}:${USER_SERVICE_DB_PORT}
    networks:
      - user_service

  service_propgroup_client:
    container_name: leprechaun-service-propgroup-client
    environment:
      - PROPGROUP_SERVICE_CLIENT_PORT
      - TRANS_SERVICE_CLIENT_HOST
      - TRANS_SERVICE_CLIENT_PORT
      - POSTGRES_USER=${PROPGROUP_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${PROPGROUP_SERVICE_DB_PASSWORD}
      - POSTGRES_HOST=${PROPGROUP_SERVICE_DB_HOST}
      - POSTGRES_PORT=${PROPGROUP_SERVICE_DB_PORT}
      - POSTGRES_DATABASE=${PROPGROUP_SERVICE_DB_DATABASE}
      - CATEGORY_SERVICE_CLIENT_HOST
      - CATEGORY_SERVICE_CLIENT_PORT
      - EVENTS_HOST
      - EVENTS_PORT
    networks:
      - api_domain
      - propgroup_service
    depends_on:
      - service_propgroup_db

  service_propgroup_db:
    container_name: leprechaun-service-propgroup-db
    build:
      context: ./services/prop_group/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=${PROPGROUP_SERVICE_DB_PASSWORD}
      - POSTGRES_USER=${PROPGROUP_SERVICE_DB_USER}
      - POSTGRES_DATABASE=${PROPGROUP_SERVICE_DB_DATABASE}
    ports:
      - ${PROPGROUP_SERVICE_DB_PORT_EXPOSE}:${PROPGROUP_SERVICE_DB_PORT}
    networks:
      - propgroup_service

  service_trans_client:
    container_name: leprechaun-service-trans-client
    environment:
      - TRANS_SERVICE_CLIENT_PORT
      - POSTGRES_USER=${TRANS_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${TRANS_SERVICE_DB_PASSWORD}
      - POSTGRES_HOST=${TRANS_SERVICE_DB_HOST}
      - POSTGRES_PORT=${TRANS_SERVICE_DB_PORT}
      - POSTGRES_DATABASE=${TRANS_SERVICE_DB_DATABASE}
      - EVENTS_HOST
      - EVENTS_PORT
    networks:
      - api_domain
      - trans_service
    depends_on:
      - service_trans_db

  service_trans_db:
    container_name: leprechaun-service-trans-db
    build:
      context: ./services/trans/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=${TRANS_SERVICE_DB_PASSWORD}
      - POSTGRES_USER=${TRANS_SERVICE_DB_USER}
      - POSTGRES_DATABASE=${TRANS_SERVICE_DB_DATABASE}
    ports:
      - ${TRANS_SERVICE_DB_PORT_EXPOSE}:${TRANS_SERVICE_DB_PORT}
    networks:
      - trans_service

  service_category_client:
    container_name: leprechaun-service-category-client
    environment:
      - CATEGORY_SERVICE_CLIENT_PORT
      - POSTGRES_USER=${CATEGORY_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${CATEGORY_SERVICE_DB_PASSWORD}
      - POSTGRES_HOST=${CATEGORY_SERVICE_DB_HOST}
      - POSTGRES_PORT=${CATEGORY_SERVICE_DB_PORT}
      - POSTGRES_DATABASE=${CATEGORY_SERVICE_DB_DATABASE}
      - CATEGORY_SERVICE_S3_HOST
      - CATEGORY_SERVICE_S3_PORT
      - CATEGORY_SERVICE_S3_PASSWORD
      - CATEGORY_SERVICE_S3_USER
      - TRANS_SERVICE_CLIENT_HOST
      - TRANS_SERVICE_CLIENT_PORT
      - PROPGROUP_SERVICE_CLIENT_HOST
      - PROPGROUP_SERVICE_CLIENT_PORT
      - EVENTS_HOST
      - EVENTS_PORT
      - PRODUCT_SERVICE_CLIENT_HOST
      - PRODUCT_SERVICE_CLIENT_PORT
    networks:
      - api_domain
      - category_service
    depends_on:
      - service_category_db
      - service_category_s3

  service_category_db:
    container_name: leprechaun-service-category-db
    build:
      context: ./services/category/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=${CATEGORY_SERVICE_DB_PASSWORD}
      - POSTGRES_USER=${CATEGORY_SERVICE_DB_USER}
      - POSTGRES_DATABASE=${CATEGORY_SERVICE_DB_DATABASE}
    ports:
      - ${CATEGORY_SERVICE_DB_PORT_EXPOSE}:${CATEGORY_SERVICE_DB_PORT}
    networks:
      - category_service

  service_category_s3:
    container_name: leprechaun-service-category-s3
    extends:
      file: docker-compose.shared.yaml
      service: s3
    environment:
      - MINIO_ROOT_USER=${CATEGORY_SERVICE_S3_USER}
      - MINIO_ROOT_PASSWORD=${CATEGORY_SERVICE_S3_PASSWORD}
    entrypoint: /docker-entrypoint-init.d/entrypoint.sh ${CATEGORY_SERVICE_S3_USER} ${CATEGORY_SERVICE_S3_PASSWORD} ${CATEGORY_SERVICE_S3_PORT} ${CATEGORY_SERVICE_S3_UI_PORT}
    volumes:
      - ./services/category/s3/data:/data
    networks:
      - category_service

  service_product_client:
    container_name: leprechaun-service-product-client
    environment:
      - PRODUCT_SERVICE_CLIENT_PORT
      - POSTGRES_USER=${PRODUCT_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${PRODUCT_SERVICE_DB_PASSWORD}
      - POSTGRES_HOST=${PRODUCT_SERVICE_DB_HOST}
      - POSTGRES_PORT=${PRODUCT_SERVICE_DB_PORT}
      - POSTGRES_DATABASE=${PRODUCT_SERVICE_DB_DATABASE}
      - PRODUCT_SERVICE_S3_HOST
      - PRODUCT_SERVICE_S3_PORT
      - PRODUCT_SERVICE_S3_PASSWORD
      - PRODUCT_SERVICE_S3_USER
      - TRANS_SERVICE_CLIENT_HOST
      - TRANS_SERVICE_CLIENT_PORT
      - CATEGORY_SERVICE_CLIENT_HOST
      - CATEGORY_SERVICE_CLIENT_PORT
      - PROPGROUP_SERVICE_CLIENT_HOST
      - PROPGROUP_SERVICE_CLIENT_PORT
      - EVENTS_HOST
      - EVENTS_PORT
    networks:
      - api_domain
      - product_service
    depends_on:
      - service_product_db
      - service_product_s3

  service_product_db:
    container_name: leprechaun-service-product-db
    build:
      context: ./services/product/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=${PRODUCT_SERVICE_DB_PASSWORD}
      - POSTGRES_USER=${PRODUCT_SERVICE_DB_USER}
      - POSTGRES_DATABASE=${PRODUCT_SERVICE_DB_DATABASE}
    ports:
      - ${PRODUCT_SERVICE_DB_PORT_EXPOSE}:${PRODUCT_SERVICE_DB_PORT}
    networks:
      - product_service

  service_product_s3:
    container_name: leprechaun-service-product-s3
    extends:
      file: docker-compose.shared.yaml
      service: s3
    environment:
      - MINIO_ROOT_USER=${PRODUCT_SERVICE_S3_USER}
      - MINIO_ROOT_PASSWORD=${PRODUCT_SERVICE_S3_PASSWORD}
    entrypoint: /docker-entrypoint-init.d/entrypoint.sh ${PRODUCT_SERVICE_S3_USER} ${PRODUCT_SERVICE_S3_PASSWORD} ${PRODUCT_SERVICE_S3_PORT} ${PRODUCT_SERVICE_S3_UI_PORT}
    volumes:
      - ./services/product/s3/data:/data
    networks:
      - product_service

  service_wishlist_client:
    container_name: leprechaun-service-wishlist-client
    environment:
      - WISHLIST_SERVICE_CLIENT_PORT
      - POSTGRES_USER=${WISHLIST_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${WISHLIST_SERVICE_DB_PASSWORD}
      - POSTGRES_HOST=${WISHLIST_SERVICE_DB_HOST}
      - POSTGRES_PORT=${WISHLIST_SERVICE_DB_PORT}
      - POSTGRES_DATABASE=${WISHLIST_SERVICE_DB_DATABASE}
      - PRODUCT_SERVICE_CLIENT_HOST
      - PRODUCT_SERVICE_CLIENT_PORT
      - EVENTS_HOST
      - EVENTS_PORT
    networks:
      - api_domain
      - wishlist_service
    depends_on:
      - service_wishlist_db

  service_wishlist_db:
    container_name: leprechaun-service-wishlist-db
    build:
      context: ./services/wishlist/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=${WISHLIST_SERVICE_DB_PASSWORD}
      - POSTGRES_USER=${WISHLIST_SERVICE_DB_USER}
      - POSTGRES_DATABASE=${WISHLIST_SERVICE_DB_DATABASE}
    ports:
      - ${WISHLIST_SERVICE_DB_PORT_EXPOSE}:${WISHLIST_SERVICE_DB_PORT}
    networks:
      - wishlist_service

  service_history_client:
    container_name: leprechaun-service-history-client
    environment:
      - HISTORY_SERVICE_CLIENT_PORT
      - POSTGRES_USER=${HISTORY_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${HISTORY_SERVICE_DB_PASSWORD}
      - POSTGRES_HOST=${HISTORY_SERVICE_DB_HOST}
      - POSTGRES_PORT=${HISTORY_SERVICE_DB_PORT}
      - POSTGRES_DATABASE=${HISTORY_SERVICE_DB_DATABASE}
      - PRODUCT_SERVICE_CLIENT_HOST
      - PRODUCT_SERVICE_CLIENT_PORT
      - EVENTS_HOST
      - EVENTS_PORT
    networks:
      - api_domain
      - history_service
    depends_on:
      - service_history_db

  service_history_db:
    container_name: leprechaun-service-history-db
    build:
      context: ./services/history/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=${HISTORY_SERVICE_DB_PASSWORD}
      - POSTGRES_USER=${HISTORY_SERVICE_DB_USER}
      - POSTGRES_DATABASE=${HISTORY_SERVICE_DB_DATABASE}
    ports:
      - ${HISTORY_SERVICE_DB_PORT_EXPOSE}:${HISTORY_SERVICE_DB_PORT}
    networks:
      - history_service

  service_subscription_client:
    container_name: leprechaun-service-subscription-client
    environment:
      - SUBSCRIPTION_SERVICE_CLIENT_PORT
      - POSTGRES_USER=${SUBSCRIPTION_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${SUBSCRIPTION_SERVICE_DB_PASSWORD}
      - POSTGRES_HOST=${SUBSCRIPTION_SERVICE_DB_HOST}
      - POSTGRES_PORT=${SUBSCRIPTION_SERVICE_DB_PORT}
      - POSTGRES_DATABASE=${SUBSCRIPTION_SERVICE_DB_DATABASE}
      - EVENTS_HOST
      - EVENTS_PORT
    networks:
      - api_domain
      - subscription_service
    depends_on:
      - service_subscription_db

  service_subscription_db:
    container_name: leprechaun-service-subscription-db
    build:
      context: ./services/subscription/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=${SUBSCRIPTION_SERVICE_DB_PASSWORD}
      - POSTGRES_USER=${SUBSCRIPTION_SERVICE_DB_USER}
      - POSTGRES_DATABASE=${SUBSCRIPTION_SERVICE_DB_DATABASE}
    ports:
      - ${SUBSCRIPTION_SERVICE_DB_PORT_EXPOSE}:${SUBSCRIPTION_SERVICE_DB_PORT}
    networks:
      - subscription_service

networks:
  server_infra:
    driver: bridge
    name: leprechaun_server_infra
  api_domain:
    driver: bridge
    name: leprechaun_api_domain
  auth_service:
    driver: bridge
    name: leprechaun_auth_service
  user_service:
    driver: bridge
    name: leprechaun_user_service
  propgroup_service:
    driver: bridge
    name: leprechaun_propgroup_service
  trans_service:
    driver: bridge
    name: leprechaun_trans_service
  category_service:
    driver: bridge
    name: leprechaun_category_service
  product_service:
    driver: bridge
    name: leprechaun_product_service
  wishlist_service:
    driver: bridge
    name: leprechaun_wishlist_service
  history_service:
    driver: bridge
    name: leprechaun_history_service
  subscription_service:
    driver: bridge
    name: leprechaun_subscription_service
