services:
  server:
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - HOSTING_PATH
    volumes:
      - ./server/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./server/conf/leprechaun.conf:/etc/nginx/conf.d/leprechaun.conf
      - ./server/conf/leprechaun.dev.conf:/etc/nginx/conf.d/leprechaun.dev.conf

  db:
    restart: unless-stopped
    volumes:
      - ./db/postgresql.conf:/app/postgresql.conf
      - ./db/pg_hba.conf:/app/pg_hba.conf

  cache:
    restart: unless-stopped
    volumes:
      - ./cache/redis.conf:/app/redis.conf

  api:
    restart: unless-stopped
    extends:
      file: docker-compose.shared.yaml
      service: node
    command: npm run dev
    volumes:
      - ./api:/app
    environment:
      - IS_DEV=true

  client_user:
    restart: unless-stopped
    extends:
      file: docker-compose.shared.yaml
      service: node
    working_dir: /app
    command: yarn dev
    volumes:
      # - client_user_trans_hosting:/app/src/public/locales:rw
      # - ./translations/dist/client_user:/app/src/public/locales
      - ./clients/user:/app
    environment:
      - IS_DEV=true
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - translations

  client_admin:
    restart: unless-stopped
    container_name: leprechaun_client_admin
    build:
      context: ./clients/admin
      dockerfile: Dockerfile
    volumes:
      # - client_admin_trans_hosting:/app/public/locales:rw
      # - ./translations/dist/client_admin:/app/public/locales
      - ./clients/admin:/app
    environment:
      - LANGS
      - VITE_APP_NAME=${APP_NAME}
      - DOMAIN
      - VITE_DOMAIN_API=${DOMAIN_API}
      - VITE_DOMAIN_MEDIA=${DOMAIN_MEDIA}
    networks:
      - client
    depends_on:
      - server

  translations:
    restart: unless-stopped
    container_name: leprechaun_translations
    extends:
      file: docker-compose.shared.yaml
      service: node
    command: yarn dev
    volumes:
      - ./translations:/app
      # - client_user_trans_hosting:/app/dist/client_user:rw
      # - client_admin_trans_hosting:/app/dist/client_admin:rw
    environment:
      - LANGS

# volumes:
#   client_user_trans_hosting:
#     driver: local
#   client_admin_trans_hosting:
#     driver: local
