version: '3.8'

services:
  postgres:
    container_name: leprechaun_postgres
    build: ./postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT} # только для GUI базы
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DATABASE

  # redis:
  #   container_name: leprechaun_redis
  #   ports:
  #     - ${REDIS_PORT}:${REDIS_PORT} # только для GUI базы

  # client:
  #   container_name: leprechaun_client

  server:
    container_name: leprechaun_server
    environment:
      - APP_NAME
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DATABASE

  nginx:
    container_name: leprechaun_nginx
    build: ./nginx
    volumes:
      - ./nginx/.http_auth:/etc/nginx/.http_auth

  # adm:
  #   container_name: leprechaun_adm
