version: '3.8'

services:
  postgres:
    restart: unless-stopped
    volumes:
      - ./postgres/postgresql.conf:/app/postgresql.conf

  redis:
    restart: unless-stopped
    volumes:
      - ./redis/redis.conf:/app/redis.conf

  server:
    restart: unless-stopped
    build: ./server
    volumes:
      - ./server:/app
    environment:
      - IS_DEV=true

  manticore:
    restart: unless-stopped
    ports:
      - ${MANTICORE_PORT}:${MANTICORE_PORT}

  client:
    restart: unless-stopped
    build: ./client
    volumes:
      - ./client:/app
    environment:
      - IS_DEV=true

  nginx:
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/leprechaun.conf:/etc/nginx/conf.d/leprechaun.conf

  admin:
    restart: unless-stopped
    build: ./admin
    volumes:
      - ./admin:/app
