version: "3.8"

services:
  server:
    container_name: leprechaun_server
    ports:
      - ${NGINX_HTTP_PORT}:80
      # - ${NGINX_HTTPS_PORT}:443
    volumes:
      - image_hosting:/var/www/img:rw
      - ./server/.http_auth:/etc/nginx/.http_auth

  db:
    container_name: leprechaun_db
    build: ./db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DATABASE

  cache:
    container_name: leprechaun_cache
    build:
      context: ./cache
      dockerfile: Dockerfile
      args:
        - REDIS_PASSWORD
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  api:
    container_name: leprechaun_api
    environment:
      - APP_NAME
      - LANGS
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DATABASE
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_USER
      - REDIS_PASSWORD
      - REDIS_SESSION_DB_NUMBER
      - REDIS_CASH_DB_NUMBER
      - HOSTING_PATH
      - MANTICORE_HOST
      - MANTICORE_PORT
      - MAIL_SMTP_HOST
      - MAIL_SMTP_PORT
      - MAIL_SENDER_ACCOUNT
      - MAIL_SENDER_PASSWORD
      - SESSION_COOKIE_SECRET
      - SESSION_AGE
      - DASHBOARD_PORTION
      - USER_HISTORY_LENGTH
      - DEFAULT_CACHE_TTL
    volumes:
      - image_hosting:/var/www/img:rw
    depends_on:
      - cache
      - db

  manticore:
    container_name: leprechaun_manticore
    image: manticoresearch/manticore
    volumes:
      - ./manticore/manticore.conf:/etc/manticoresearch/manticore.conf
    depends_on:
      - db

  client:
    container_name: leprechaun_client
    environment:
      - APP_NAME
      - LANGS
      - PORT=80
    depends_on:
      - api

volumes:
  image_hosting:

networks:
  default:
    name: leprechaun_net
