version: "3.8"

services:
  server:
    restart: on-failure:5
    build:
      context: ./server
      dockerfile: Dockerfile.prod
      args:
        - ADMIN_CLIENT_PATH
        - HOSTING_PATH
        - APP_NAME
        - LANGS
        - DOMAIN
        - DOMAIN_MEDIA
        - DOMAIN_API
    depends_on:
      - client_user

  db:
    restart: on-failure:5

  cache:
    restart: on-failure:5

  api:
    restart: on-failure:5
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    environment:
      - IS_DEV=false
      - DEV_MAIL_RECIEVER

  manticore:
    restart: on-failure:5

  client_user:
    restart: on-failure:5
    build:
      context: ./clients/user
      dockerfile: Dockerfile.prod
      args:
        - APP_NAME
        - LANGS
        - DOMAIN
        - DOMAIN_MEDIA
        - DOMAIN_API
        - CURRENCY_SYMBOL
    volumes:
      - ./clients/user/logs:/app/logs
    environment:
      - IS_DEV=false
