services:
  server:
    container_name: leprechaun_server
    networks:
      client:
        aliases:
          - api.leprechaun.loc
          - media.leprechaun.loc
      api:
    ports:
      - ${WEB_SERVER_PORT}:80
    volumes:
      - image_hosting:/var/www/img:rw
      - ./server/.http_auth:/etc/nginx/.http_auth
    depends_on:
      - api

  db:
    container_name: leprechaun_db
    networks:
      - api
      - db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - ${DB_PORT_EXPOSE}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DATABASE=${DB_DATABASE}

  cache:
    container_name: leprechaun_cache
    networks:
      - api
    build:
      context: ./cache
      dockerfile: Dockerfile
      args:
        - REDIS_PASSWORD:${CACHE_PASSWORD}
    ports:
      - ${CACHE_PORT_EXPOSE}:${CACHE_PORT}

  api:
    container_name: leprechaun_api
    networks:
      - api
    environment:
      - HOST_NAME
      - CORS_DOMAINS
      - DOMAIN
      - DOMAIN_ADM
      - APP_NAME
      - LANGS
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DATABASE=${DB_DATABASE}
      - SE_HOST
      - SE_PORT
      - SE_USER
      - SE_PASSWORD
      - CACHE_HOST
      - CACHE_PORT_EXPOSE
      - CACHE_PORT
      - CACHE_USER
      - CACHE_PASSWORD
      - CACHE_DB_NUMBER
      - HOSTING_PATH
      - MAIL_SMTP_HOST
      - MAIL_SMTP_PORT
      - MAIL_SENDER_ACCOUNT
      - MAIL_SENDER_PASSWORD
      - DEV_MAIL_RECIEVER
      - SESSION_COOKIE_SECRET
      - SESSION_AGE
      - DASHBOARD_PORTION
      - USER_WISHLIST_LENGTH
      - USER_HISTORY_LENGTH
      - DEFAULT_CACHE_TTL
      - PRODUCT_PUBLIC_IMAGE_AMOUNT
    volumes:
      - image_hosting:/var/www/img:rw
    depends_on:
      - cache
      - db

  client_user:
    container_name: leprechaun_client_user
    networks:
      - client
    environment:
      - APP_NAME
      - LANGS
      - DOMAIN
      - DOMAIN_MEDIA
      - DOMAIN_API
      - CURRENCY_SYMBOL
    depends_on:
      - server

volumes:
  image_hosting:

networks:
  api:
    driver: bridge
    name: leprechaun_api
  db:
    driver: bridge
    name: leprechaun_db
  client:
    driver: bridge
    name: leprechaun_client
