services:
  server:
    container_name: leprechaun_server
    networks:
      client:
        aliases:
          - api.leprechaun.loc
          - media.leprechaun.loc
          - leprechaun.loc
      api:
    ports:
      - ${WEB_SERVER_PORT}:80
    volumes:
      - image_hosting:/var/www/img:rw
      - ./server/.http_auth:/etc/nginx/.http_auth
    depends_on:
      - api_gateway_private
      - api_gateway_public

  db:
    container_name: leprechaun_db
    networks:
      - api
      - db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - ${DB_PORT_EXPOSE}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DATABASE=${DB_DATABASE}

  cache:
    container_name: leprechaun_cache
    networks:
      - api
    build:
      context: ./cache
      dockerfile: Dockerfile
      args:
        - REDIS_PASSWORD:${CACHE_PASSWORD}
    ports:
      - ${CACHE_PORT_EXPOSE}:${CACHE_PORT}

  api_gateway_private:
    container_name: leprechaun_api_gateway_private
    networks:
      - api
    environment:
      - HOST_NAME
      - CORS_DOMAINS
      - DOMAIN_PUBLIC
      - DOMAIN_PRIVATE
      - APP_NAME
      - LANGS
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DATABASE=${DB_DATABASE}
      - JWT_ACCESS_TOKEN_KEY
      - JWT_ACCESS_TOKEN_TTL
      - JWT_REFRESH_TOKEN_KEY
      - JWT_REFRESH_TOKEN_TTL
    volumes:
      - image_hosting:/var/www/img:rw
    depends_on:
      - db

  api_gateway_public:
    container_name: leprechaun_api_gateway_public
    networks:
      - api
    environment:
      - HOST_NAME
      - CORS_DOMAINS
      - DOMAIN_PUBLIC
      - DOMAIN_PRIVATE
      - APP_NAME
      - LANGS
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DATABASE=${DB_DATABASE}
      - SESSION_COOKIE_SECRET
      - SESSION_TLL
      - USER_HISTORY_LENGTH
    depends_on:
      - cache
      - db

  client_user:
    container_name: leprechaun_client_user
    networks:
      - client
    environment:
      - APP_NAME
      - LANGS
      - NEXT_PUBLIC_LANGS=${LANGS}
      - DOMAIN_PUBLIC
      - DOMAIN_MEDIA
      - DOMAIN_API
      - NEXT_PUBLIC_DOMAIN_API=${DOMAIN_API}
      - CURRENCY_SYMBOL
    depends_on:
      - server

volumes:
  image_hosting:

networks:
  api:
    driver: bridge
    name: leprechaun_api
  db:
    driver: bridge
    name: leprechaun_db
  client:
    driver: bridge
    name: leprechaun_client
