version: "3.8"

services:
  server:
    container_name: leprechaun_server
    ports:
      - ${WEB_SERVER_PORT}:80
    volumes:
      - image_hosting:/var/www/img:rw
      - ./server/.http_auth:/etc/nginx/.http_auth

  db:
    container_name: leprechaun_db
    build: ./db
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DATABASE=${DB_DATABASE}

  cache:
    container_name: leprechaun_cache
    build:
      context: ./cache
      dockerfile: Dockerfile
      args:
        - REDIS_PASSWORD:${CACHE_PASSWORD}
    ports:
      - ${CACHE_PORT}:${CACHE_CONTAINER_PORT}

  api:
    container_name: leprechaun_api
    environment:
      - DOMAIN
      - DOMAIN_ADM
      - APP_NAME
      - LANGS
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DATABASE=${DB_DATABASE}
      - CACHE_HOST
      - CACHE_PORT
      - CACHE_CONTAINER_PORT
      - CACHE_USER
      - CACHE_PASSWORD
      - CACHE_DB_NUMBER
      - HOSTING_PATH
      - MAIL_SMTP_HOST
      - MAIL_SMTP_PORT
      - MAIL_SENDER_ACCOUNT
      - MAIL_SENDER_PASSWORD
      - SESSION_COOKIE_SECRET
      - SESSION_AGE
      - DASHBOARD_PORTION
      - USER_HISTORY_LENGTH
      - DEFAULT_CACHE_TTL
      - PRODUCT_PUBLIC_IMAGE_AMOUNT
    volumes:
      - image_hosting:/var/www/img:rw
    depends_on:
      - cache
      - db

  client_user:
    container_name: leprechaun_client_user
    environment:
      - APP_NAME
      - LANGS
      - DOMAIN
      - DOMAIN_MEDIA
      - DOMAIN_API
      - CURRENCY_SYMBOL
    depends_on:
      - api

volumes:
  image_hosting:

networks:
  default:
    name: leprechaun_net
