version: "3.8"

services:
    nginx:
        restart: unless-stopped
        build:
            context: ./nginx
            dockerfile: Dockerfile
            args:
                - HOSTING_PATH
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf/leprechaun.conf:/etc/nginx/conf.d/leprechaun.conf
            - ./nginx/conf/leprechaun.dev.conf:/etc/nginx/conf.d/leprechaun.dev.conf

    postgres:
        restart: unless-stopped
        volumes:
            - ./postgres/postgresql.conf:/app/postgresql.conf

    redis:
        restart: unless-stopped
        volumes:
            - ./redis/redis.conf:/app/redis.conf

    server:
        restart: unless-stopped
        build: ./server
        volumes:
            - ./server:/app
        environment:
            - IS_DEV=true

    manticore:
        restart: unless-stopped
        ports:
            - ${MANTICORE_PORT}:${MANTICORE_PORT}

    client:
        restart: unless-stopped
        build: ./client
        volumes:
            - ./client:/app
        environment:
            - IS_DEV=true

    admin:
        restart: unless-stopped
        build: ./admin
        volumes:
            - ./admin:/app
