services:
  server:
    container_name: leprechaun_server
    networks:
      client:
        aliases:
          - api.leprechaun.loc
          - media.leprechaun.loc
          - leprechaun.loc
      api:
    ports:
      - ${WEB_SERVER_PORT}:80
    volumes:
      - image_hosting:/var/www/img:rw
      - ./server/.http_auth:/etc/nginx/.http_auth
    depends_on:
      - api_gateway_private
      - api_gateway_public
      - api_gateway_ws
      - client_public

  db_main:
    container_name: leprechaun_db_main
    networks:
      - api
      - db
    build:
      context: ./db/main
      dockerfile: Dockerfile
    ports:
      - ${DB_PORT_EXPOSE}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DATABASE=${DB_DATABASE}

  db_cache:
    container_name: leprechaun_db_cache
    networks:
      - api
    build:
      context: ./db/cache
      dockerfile: Dockerfile
      args:
        - REDIS_PASSWORD=${CACHE_PASSWORD}
    environment:
      - REDIS_PASSWORD=${CACHE_PASSWORD}
    ports:
      - ${CACHE_PORT_EXPOSE}:${CACHE_PORT}

  broker_net:
    container_name: leprechaun_broker_net
    ports:
      - ${BROKER_NET_PORT_EXPOSE}:5672
    networks:
      - api

  api_gateway_private:
    container_name: leprechaun_api_gateway_private
    networks:
      - api
    environment:
      - HOST_NAME
      - DOMAIN_PUBLIC
      - DOMAIN_PRIVATE
      - APP_NAME
      - LANGS
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DATABASE=${DB_DATABASE}
      - JWT_ACCESS_TOKEN_KEY
      - JWT_ACCESS_TOKEN_TTL
      - JWT_REFRESH_TOKEN_KEY
      - JWT_REFRESH_TOKEN_TTL
      - CACHE_HOST
      - CACHE_PORT
      - CACHE_USER
      - CACHE_PASSWORD
      - CACHE_DB_NUMBER
      - DEFAULT_CACHE_TTL
      - BROKER_NET_HOST
      - BROKER_NET_PORT
      - HOSTING_PATH
    volumes:
      - image_hosting:/var/www/img:rw
    depends_on:
      - db_main

  api_gateway_public:
    container_name: leprechaun_api_gateway_public
    networks:
      - api
    environment:
      - HOST_NAME
      - DOMAIN_PUBLIC
      - DOMAIN_PRIVATE
      - APP_NAME
      - LANGS
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DATABASE=${DB_DATABASE}
      - SESSION_COOKIE_SECRET
      - SESSION_TLL
      - USER_HISTORY_LENGTH
      - CACHE_HOST
      - CACHE_PORT
      - CACHE_USER
      - CACHE_PASSWORD
      - CACHE_DB_NUMBER
      - DEFAULT_CACHE_TTL
      - BROKER_NET_HOST
      - BROKER_NET_PORT
    depends_on:
      - db_cache
      - db_main

  api_gateway_ws:
    container_name: leprechaun_api_gateway_ws
    networks:
      - api
    environment:
      - SESSION_COOKIE_SECRET
      - SOCKET_HOST
      - SOCKET_PORT
      - SOCKET_USER
      - SOCKET_PASSWORD
      - SOCKET_DB_NUMBER
      - DOMAIN_PUBLIC
      - DOMAIN_PRIVATE
      - BROKER_NET_HOST
      - BROKER_NET_PORT
    depends_on:
      - db_cache

  client_public:
    container_name: leprechaun_client_public
    networks:
      - client
    environment:
      - APP_NAME
      - LANGS
      - NEXT_PUBLIC_LANGS=${LANGS}
      - DOMAIN_PUBLIC
      - DOMAIN_MEDIA
      - DOMAIN_API
      - NEXT_PUBLIC_DOMAIN_API=${DOMAIN_API}
      - CURRENCY_SYMBOL
    depends_on:
      - api_gateway_public

volumes:
  image_hosting:

networks:
  api:
    driver: bridge
    name: leprechaun_api
  db:
    driver: bridge
    name: leprechaun_db_main
  client:
    driver: bridge
    name: leprechaun_client
