version: "3.8"

services:
  server:
    restart: on-failure:5
    build:
      context: ./server
      dockerfile: Dockerfile.prod
      args:
        - ADMIN_CLIENT_PATH
        - HOSTING_PATH
        - DOMAIN_MEDIA
        - DOMAIN_API
    depends_on:
      - client

  db:
    restart: on-failure:5

  cache:
    restart: on-failure:5

  api:
    restart: on-failure:5
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    environment:
      - IS_DEV=false
      - DEV_MAIL_RECIEVER

  manticore:
    restart: on-failure:5

  client:
    restart: on-failure:5
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    environment:
      - IS_DEV=false
