version: '3.8'

services:
  postgres:
    container_name: leprechaun_postgres
    build: ./postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DATABASE

  # redis:
  #   container_name: leprechaun_redis
  #   ports:
  #     - ${REDIS_PORT}:${REDIS_PORT}

  server:
    container_name: leprechaun_server
    environment:
      - APP_NAME
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DATABASE
    volumes:
      - image_hosting:/var/www/img:rw

  client:
    container_name: leprechaun_client
    environment:
      - APP_NAME

  nginx:
    container_name: leprechaun_nginx
    build: ./nginx
    depends_on:
      - admin
      - server
      - client
    volumes:
      - image_hosting:/var/www/img:rw
      - ./nginx/.http_auth:/etc/nginx/.http_auth

  admin:
    container_name: leprechaun_admin
    environment:
      - APP_NAME

volumes:
  image_hosting:
