version: "3.8"

services:
    nginx:
        restart: on-failure:5
        build:
            context: ./nginx
            dockerfile: Dockerfile.prod
            args:
                - ADMIN_CLIENT_PATH
                - HOSTING_PATH
        ports:
            - 84:80
        depends_on:
            - client

    postgres:
        restart: on-failure:5

    redis:
        restart: on-failure:5

    server:
        restart: on-failure:5
        build:
            context: ./server
            dockerfile: Dockerfile.prod
        environment:
            - IS_DEV=false
            - DEV_MAIL_RECIEVER

    manticore:
        restart: on-failure:5

    client:
        restart: on-failure:5
        build:
            context: ./client
            dockerfile: Dockerfile.prod
        environment:
            - IS_DEV=false
