services:
  server:
    restart: on-failure:5
    build:
      context: ./server
      dockerfile: Dockerfile.prod
      args:
        - ADMIN_CLIENT_PATH
        - HOSTING_PATH
        - APP_NAME
        - LANGS
        - DOMAIN
        - DOMAIN_MEDIA
        - DOMAIN_API

  db:
    restart: on-failure:5

  cache:
    restart: on-failure:5

  api:
    restart: on-failure:5
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    environment:
      - IS_DEV=false
    volumes:
      - ./api/logs:/app/logs

  client_user:
    restart: on-failure:5
    build:
      context: ./clients/user
      dockerfile: Dockerfile.prod
      args:
        - APP_NAME
        - LANGS
        - DOMAIN
        - DOMAIN_MEDIA
        - DOMAIN_API
        - CURRENCY_SYMBOL
    environment:
      - IS_DEV=false

  se_client:
    restart: on-failure:5
    environment:
      - ELASTICSEARCH_USERNAME=${SE_CLIENT_USERNAME}
      - ELASTICSEARCH_PASSWORD=${SE_CLIENT_PASSWORD}
