version: '3.8'

services:
  nginx:
    container_name: leprechaun_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - HOSTING_PATH
    volumes:
      - image_hosting:/var/www/img:rw
      - ./nginx/.http_auth:/etc/nginx/.http_auth
    depends_on:
      - admin
      - client

  postgres:
    container_name: leprechaun_postgres
    build: ./postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DATABASE

  redis:
    container_name: leprechaun_redis
    build:
      context: ./redis
      dockerfile: Dockerfile
      args:
        - REDIS_PASSWORD
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  server:
    container_name: leprechaun_server
    environment:
      - APP_NAME
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DATABASE
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_USER
      - REDIS_PASSWORD
      - REDIS_SESSION_DB_NUMBER
      - REDIS_CASH_DB_NUMBER
      - HOSTING_PATH
      - MANTICORE_HOST
      - MANTICORE_PORT
      - MAIL_SMTP_HOST
      - MAIL_SMTP_PORT
      - MAIL_SENDER_ACCOUNT
      - MAIL_SENDER_PASSWORD
      - SESSION_COOKIE_SECRET
      - SESSION_AGE
      - DASHBOARD_PORTION
      - USER_HISTORY_LENGTH
      - DEFAULT_CACHE_TTL
    volumes:
      - image_hosting:/var/www/img:rw
    depends_on:
      - redis
      - postgres

  manticore:
    container_name: leprechaun_manticore
    image: manticoresearch/manticore
    volumes:
      - ./manticore/manticore.conf:/etc/manticoresearch/manticore.conf
    depends_on:
      - postgres

  client:
    container_name: leprechaun_client
    environment:
      - APP_NAME
      - PORT=80
    depends_on:
      - server

  admin:
    container_name: leprechaun_admin
    environment:
      - APP_NAME
    depends_on:
      - server

volumes:
  image_hosting:

networks:
  default:
    name: leprechaun_net
