FROM node:16.15.0-alpine3.14

WORKDIR /app

COPY package.json package-lock.json .

RUN npm install

COPY . .

#RUN yarn --network-timeout 100000

#CMD yarn build && yarn prod
CMD npm run build && npm run prod
