index_products:
	@docker exec leprechaun_se indexer products_index --config /etc/manticoresearch/manticore.conf --rotate

index_all:
	@docker exec leprechaun_se indexer --all --config /etc/manticoresearch/manticore.conf --rotate
