index_products:
	@docker exec leprechaun_manticore indexer products_index --config /etc/manticoresearch/manticore.conf --rotate

index_all:
	@docker exec leprechaun_manticore indexer --all --config /etc/manticoresearch/manticore.conf --rotate
