index_products:
	@docker exec leprechaun_sphinx indexer products_index --config /opt/sphinx/conf/sphinx.conf --rotate

index_all:
	@docker exec leprechaun_sphinx indexer --all --config /opt/sphinx/conf/sphinx.conf --rotate
