index_products:
	@docker exec leprechaun_sphinx indexer products_index --config /etc/sphinx/sphinx.conf --rotate

index_all:
	@docker exec leprechaun_sphinx indexer --all --config /etc/sphinx/sphinx.conf --rotate
