#!/bin/bash

set -e
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
	CREATE SUBSCRIPTION allsub CONNECTION 'host=$MASTER_DB_HOST user=$MASTER_DB_USER dbname=$MASTER_DB_NAME password=$MASTER_DB_PASS' PUBLICATION allpub;
EOSQL
