// segments
export const PROPERTY_GROUP_PATH_SEGMENT = 'propertygroup';
export const PROPERTY_GROUP_CREATE_PATH_SEGMENT = 'create';

// paths
export const PROPERTY_GROUP_PATH = `/${PROPERTY_GROUP_PATH_SEGMENT}`;
export const PROPERTY_GROUP_CREATE_PATH = `/${PROPERTY_GROUP_PATH_SEGMENT}/${PROPERTY_GROUP_CREATE_PATH_SEGMENT}`;
