name: Deploy remote test project

on:
  push:
    branches: [test]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch test branch
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: "root"
          key: ${{ secrets.TEST_SERVER_SSH_KEY }}
          script: |
            cd /var/www/Leprechaun
            git reset --hard HEAD
            git checkout test
            git pull origin test
      - name: Rebuild && up containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: "root"
          key: ${{ secrets.TEST_SERVER_SSH_KEY }}
          script: |
            cd /var/www/Leprechaun
            make build_prod

